name: Release on multiple platforms

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  release-windows:
    runs-on: windows-latest
    name: Build on Windows-latests
    steps:
      #checkout code
      - name: Checkout code
        id: checkout_code
        uses: actions/checkout@v4

      #Setup Vulkan SDK
      - name: Install Vulkan SDK
        uses: humbletim/install-vulkan-sdk@v1.1.1
        with:
         version: latest
         cache: true

      #Locate MSBuild.eze and add to PATH
      - name: Add MSBuild to PATH
        id: setup_msbuild
        uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: x64
          
      #Run MSBuild Release
      - name: Run MSBuild Release
        id: run_msbuild_release
        working-directory: .\
        run: msbuild.exe .\ -t:VulVoxOptimizationProject -property:Configuration=Release -property:Platform=x64

      - uses: actions/upload-artifact@v4
        with:
          name: windows-release-artifact
          path: x64/Release

      - uses: actions/download-artifact@v4
        with:
          name: windows-release-artifact
          
      - name: Release Windows
        uses: googleapis/release-please-action@v4
        id: release_windows
        with:
          token: ${{secrets.VUL_RELEASE_TOKEN}}
          manifest-file: .release-please-manifest.json
          release-type: simple

      - name: Print release output
        continue-on-error: true
        run: |
            echo "Release outputs:"
            echo "${{ toJson(steps.release_windows.outputs) }}"
 
      - name: Upload Release Artifact
        env:
          GITHUB_TOKEN: ${{ secrets.VUL_RELEASE_TOKEN }}
        run: gh release upload ${{ needs.release-please.outputs.windows-release--tag_name }} windows-release-artifact.zip

