name: Release on multiple platforms

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  release-windows:
    runs-on: windows-latest
    name: Build on Windows-latests
    steps:
      #checkout code
      - name: Checkout code
        id: checkout_code
        uses: actions/checkout@v4

      #Setup Vulkan SDK
      - name: Install Vulkan SDK
        uses: humbletim/install-vulkan-sdk@v1.1.1
        with:
         version: latest
         cache: true

      #Locate MSBuild.eze and add to PATH
      - name: Add MSBuild to PATH
        id: setup_msbuild
        uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: x64
          
      #Run MSBuild Release
      - name: Run MSBuild Release
        id: run_msbuild_release
        working-directory: .\
        run: msbuild.exe .\ -t:VulVoxOptimizationProject -property:Configuration=Release -property:Platform=x64
        
      - name: Release Windows
        uses: googleapis/release-please-action@v4
        with:
          token: ${{secrets.VUL_RELEASE_TOKEN}}
          path: x64\Release
          release-type: simple
